"""initial schema

Revision ID: 358991837047
Revises: 
Create Date: 2026-08-20 23:45:32.581673
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '358991837047'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('receive_name', sa.String(length=64), nullable=False),
    sa.Column('estimate_income', sa.Float(), nullable=False),
    sa.Column('ad_network_platform_name', sa.String(length=64), nullable=False),
    sa.Column('is_lottery', sa.Integer(), nullable=False),
    sa.Column('is_rw', sa.Integer(), nullable=False),
    sa.Column('is_type', sa.Integer(), nullable=False),
    sa.Column('is_fu', sa.Integer(), nullable=False),
    sa.Column('fu_type', sa.Integer(), nullable=False),
    sa.Column('is_look', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('trans_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('security_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('game_ad_status', sa.Integer(), nullable=False),
    sa.Column('ht_status', sa.Integer(), nullable=False),
    sa.Column('is_gx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('coin_before', sa.Float(), nullable=False),
    sa.Column('coin', sa.Float(), nullable=False),
    sa.Column('coin_after', sa.Float(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('game_icon', sa.String(length=255), nullable=False),
    sa.Column('game_key', sa.String(length=128), nullable=False),
    sa.Column('game_url', sa.String(length=255), nullable=False),
    sa.Column('game_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('ad_status', sa.Integer(), nullable=False),
    sa.Column('lucky_enable', sa.Integer(), nullable=False),
    sa.Column('is_landscape', sa.Integer(), nullable=False),
    sa.Column('is_game', sa.Integer(), nullable=False),
    sa.Column('is_mobile', sa.Integer(), nullable=False),
    sa.Column('is_imei', sa.Integer(), nullable=False),
    sa.Column('raffle_num', sa.Integer(), nullable=False),
    sa.Column('star_countdown', sa.Float(), nullable=False),
    sa.Column('over_countdown', sa.Float(), nullable=False),
    sa.Column('star_coin', sa.Float(), nullable=False),
    sa.Column('over_coin', sa.Float(), nullable=False),
    sa.Column('coin_get', sa.Float(), nullable=False),
    sa.Column('exchange_num', sa.Integer(), nullable=False),
    sa.Column('commission_status', sa.Integer(), nullable=False),
    sa.Column('commission_source', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('tixian_price', sa.String(length=255), nullable=False),
    sa.Column('tixian_coin', sa.String(length=255), nullable=False),
    sa.Column('tixian_wx', sa.Integer(), nullable=False),
    sa.Column('wx_appid', sa.String(length=128), nullable=False),
    sa.Column('wx_secert', sa.String(length=128), nullable=False),
    sa.Column('other_url', sa.String(length=255), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('card_no', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('coin', sa.Float(), nullable=False),
    sa.Column('freeze_coin', sa.Float(), nullable=False),
    sa.Column('coin_user', sa.Float(), nullable=False),
    sa.Column('coin_user_month', sa.Float(), nullable=False),
    sa.Column('coin_user_day', sa.Float(), nullable=False),
    sa.Column('vip', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('exchange_enable', sa.Integer(), nullable=False),
    sa.Column('game_addiction_enable', sa.Integer(), nullable=False),
    sa.Column('game_addiction_time', sa.String(length=64), nullable=False),
    sa.Column('is_white', sa.Integer(), nullable=False),
    sa.Column('ht_status', sa.Integer(), nullable=False),
    sa.Column('ht_id', sa.Integer(), nullable=False),
    sa.Column('ht_top_id', sa.Integer(), nullable=False),
    sa.Column('beishu', sa.Float(), nullable=False),
    sa.Column('percent_zhi', sa.Float(), nullable=False),
    sa.Column('percent_jian', sa.Float(), nullable=False),
    sa.Column('percent_dai', sa.Float(), nullable=False),
    sa.Column('percent_dai_two', sa.Float(), nullable=False),
    sa.Column('last_login_ip', sa.String(length=64), nullable=False),
    sa.Column('last_login_time', sa.String(length=64), nullable=False),
    sa.Column('last_login_device_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tagcode', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('hardware_main_id', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subsidies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tx_price', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('pics', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('sub_msg', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('receive_name', sa.String(length=64), nullable=False),
    sa.Column('receive_tel', sa.String(length=64), nullable=False),
    sa.Column('receive_address', sa.String(length=255), nullable=False),
    sa.Column('exchange_value', sa.Float(), nullable=False),
    sa.Column('exchange_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('plan_status', sa.Integer(), nullable=False),
    sa.Column('sub_msg', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawals')
    op.drop_table('subsidies')
    op.drop_table('risk_records')
    op.drop_table('members')
    op.drop_table('games')
    op.drop_table('coin_logs')
    op.drop_table('agents')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('ad_records')
    # ### end Alembic commands ###
