"""expand ad record details

Revision ID: 8db735c18587
Revises: 358991837047
Create Date: 2026-08-21 00:03:31.706441
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8db735c18587'
down_revision: Union[str, None] = '358991837047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_records', sa.Column('parent_id', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('ad_records', sa.Column('parent_payment_name', sa.String(length=64), server_default=sa.text("''"), nullable=False))
    op.add_column('ad_records', sa.Column('user_account', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('ad_records', sa.Column('game_name', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('ad_records', sa.Column('ecpm', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.add_column('ad_records', sa.Column('coin', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.add_column('ad_records', sa.Column('reward_type', sa.String(length=32), server_default=sa.text("'领取'"), nullable=False))
    op.add_column('ad_records', sa.Column('ad_type', sa.String(length=32), server_default=sa.text("'激励'"), nullable=False))
    op.add_column('ad_records', sa.Column('sub_ad_type', sa.String(length=32), server_default=sa.text("''"), nullable=False))
    op.add_column('ad_records', sa.Column('status', sa.String(length=32), server_default=sa.text("'成功'"), nullable=False))
    op.add_column('ad_records', sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ad_records', sa.Column('ad_code', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_records', 'ad_code')
    op.drop_column('ad_records', 'watched_at')
    op.drop_column('ad_records', 'status')
    op.drop_column('ad_records', 'sub_ad_type')
    op.drop_column('ad_records', 'ad_type')
    op.drop_column('ad_records', 'reward_type')
    op.drop_column('ad_records', 'coin')
    op.drop_column('ad_records', 'ecpm')
    op.drop_column('ad_records', 'game_name')
    op.drop_column('ad_records', 'user_account')
    op.drop_column('ad_records', 'parent_payment_name')
    op.drop_column('ad_records', 'parent_id')
    # ### end Alembic commands ###
