"""Recovered import mappings and alert labels from the original backend."""

AD_ALERT_SEVERITY_LABELS = {'high': '高', 'low': '低', 'medium': '中'}

AD_ALERT_SEVERITY_ORDER = {'high': 3, 'low': 1, 'medium': 2}

AD_ALERT_TYPE_LABELS = {'duplicate_request_id': '请求ID重复',
 'group_mismatch': '分组异常',
 'import_error': '导入失败',
 'missing_request_id': '请求ID缺失',
 'zero_coin': '金币为零',
 'zero_ecpm': 'ECPM 为零'}

AD_IMPORT_BATCH_FIELDS = ['id',
 'file_name',
 'operator_id',
 'operator_name',
 'total',
 'accepted',
 'rejected',
 'status',
 'created_at',
 'updated_at']

AD_IMPORT_ERROR_FIELDS = ['id', 'batch_id', 'row_number', 'request_id', 'message', 'raw_data', 'created_at']

AD_IMPORT_FIELD_ALIASES = {'ECPM': 'ecpm',
 'ID': 'id',
 'ad_code': 'ad_code',
 'ad_group': 'ad_group',
 'ad_network_platform_name': 'ad_network_platform_name',
 'ad_type': 'ad_type',
 'agent_id': 'agent_id',
 'coin': 'coin',
 'ecpm': 'ecpm',
 'estimate_income': 'estimate_income',
 'fu_type': 'fu_type',
 'game_id': 'game_id',
 'game_name': 'game_name',
 'id': 'id',
 'is_fu': 'is_fu',
 'is_look': 'is_look',
 'is_lottery': 'is_lottery',
 'is_rw': 'is_rw',
 'parent_id': 'parent_id',
 'parent_payment_name': 'parent_payment_name',
 'receive_name': 'receive_name',
 'request_id': 'request_id',
 'reward_type': 'reward_type',
 'status': 'status',
 'sub_ad_type': 'sub_ad_type',
 'trans_id': 'trans_id',
 'user_account': 'user_account',
 'user_id': 'user_id',
 'watched_at': 'watched_at',
 '上级ID': 'parent_id',
 '上级支付宝姓名': 'parent_payment_name',
 '交易trans_id': 'trans_id',
 '代理商ID': 'agent_id',
 '任务': 'is_rw',
 '会员ID': 'user_id',
 '副广告类型': 'sub_ad_type',
 '副广类型': 'fu_type',
 '原始广告类型': 'ad_type',
 '奖励类型': 'reward_type',
 '广告request_id': 'request_id',
 '广告代码位': 'ad_code',
 '广告分组': 'ad_group',
 '广告平台': 'ad_network_platform_name',
 '广告类型': 'ad_type',
 '抽奖': 'is_lottery',
 '支付宝姓名': 'receive_name',
 '是否副广': 'is_fu',
 '有效观看': 'is_look',
 '游戏ID': 'game_id',
 '游戏名称': 'game_name',
 '状态': 'status',
 '用户ID': 'user_id',
 '用户账号': 'user_account',
 '观看时间': 'watched_at',
 '金币': 'coin',
 '预估收益': 'estimate_income'}

AD_IMPORT_NUMERIC_FIELDS = {'agent_id': int,
 'coin': float,
 'ecpm': float,
 'estimate_income': float,
 'fu_type': int,
 'game_id': int,
 'is_fu': int,
 'is_look': int,
 'is_lottery': int,
 'is_rw': int,
 'is_type': int,
 'parent_id': int,
 'user_id': int}

AD_IMPORT_STRING_FIELDS = {'ad_code',
 'ad_group',
 'ad_network_platform_name',
 'ad_type',
 'game_name',
 'parent_payment_name',
 'receive_name',
 'request_id',
 'reward_type',
 'status',
 'sub_ad_type',
 'trans_id',
 'user_account'}

COINLOG_FIELDS = ['id',
 'user_id',
 'agent_id',
 'game_id',
 'coin_before',
 'coin',
 'coin_after',
 'type',
 'remark',
 'created_at']

RISK_FIELDS = ['id',
 'user_id',
 'agent_id',
 'game_id',
 'tagcode',
 'tags',
 'hardware_main_id',
 'ip',
 'action',
 'risk_score',
 'risk_level',
 'created_at']

SUBSIDY_FIELDS = ['id',
 'user_id',
 'agent_id',
 'game_id',
 'tx_price',
 'price',
 'pics',
 'status',
 'sub_msg',
 'audit_operator_id',
 'audit_operator_name',
 'audited_at',
 'created_at']

WITHDRAWAL_FIELDS = ['id',
 'user_id',
 'agent_id',
 'game_id',
 'receive_name',
 'receive_tel',
 'receive_address',
 'exchange_value',
 'exchange_type',
 'status',
 'plan_status',
 'sub_msg',
 'reason',
 'audit_operator_id',
 'audit_operator_name',
 'audited_at',
 'transfer_operator_id',
 'transfer_operator_name',
 'transferred_at',
 'created_at']
